Making the 3.0 bundle work again. I assume there really shouldn't be a double extension here?
For reference, here's the error I got before this fix was applied:

{{{
Traceback (most recent call last):
  File "/var/folders/-P/-P2+bQpqH-OIb1m7A2AAPk+++TI/-Tmp-/tmpE4D3yp", line 11, in ?
    execfile('/Users/limi/Projects/Plone/buildouts/3.0/src/plone.app.iterate/setup.py')
  File "/Users/limi/Projects/Plone/buildouts/3.0/src/plone.app.iterate/setup.py", line 9, in ?
    long_description=\
IOError: [Errno 2] No such file or directory: 'docs/HISTORY.txt.txt'
While:
  Installing.
  Processing develop directory '/Users/limi/Projects/Plone/buildouts/3.0/src/plone.app.iterate'.

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:

AssertionError:
}}}


svn path=/plone.app.iterate/trunk/; revision=19069